name: "pre-release"
on:
  push:
    branches:
      - "master"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v14
        with:
          name: kmein
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: assets
        run: nix build $GITHUB_WORKSPACE#assets --out-link assets
      - run: zip assets.zip assets/*
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Assets release"
          files: |
            assets.zip
            assets/*.csv
